" Настройки для поддержки xdg дирректорий
set undodir=$XDG_CACHE_HOME/vim/undo
set directory=$XDG_CACHE_HOME/vim/swap
set backupdir=$XDG_CACHE_HOME/vim/backup
set viminfo+='1000,n$XDG_CACHE_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIMRUNTIME

" цветовая схема
set t_Co=256                    " включаем поддержку 256 цветов
"
set background=dark

runtime plugins.vim
runtime plugin_options.vim
runtime options.vim
runtime keymap.vim

" переопределять переменные для некоторых типов файлов
autocmd! FileType text setlocal wrap

:command! W set buftype=nowrite | silent execute ':%w !sudo tee %' | set buftype= | e! %

" Remember last location in file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal g'\"" | endif
endif

" Перезаписать и перечитать .vimrc сразу после его изменения
autocmd! bufwritepost $MYVIMRC source $MYVIMRC

